spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: rootroot
    url: jdbc:mysql://localhost:3306/test2?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC

mybatis:
  type-aliases-package: com.springboot.mybatis.pojo
  mapper-locations: classpath:mapper/*.xml

server:
  port: 8082
debug: true